include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # ---- 风格相关 ----
    always_declare_return_types: true       # 函数必须声明返回类型
    always_put_required_named_parameters_first: true
    always_use_package_imports: true        # 强制使用 package: 导入，避免相对路径混乱
    avoid_print: true                       # 禁止使用 print，建议用 logger
    avoid_relative_lib_imports: true        # lib 内部不能用相对路径 import
    prefer_const_constructors: true         # 尽量使用 const
    prefer_const_declarations: true
    prefer_final_fields: true               # 成员变量尽量 final
    prefer_final_locals: true               # 局部变量尽量 final
    unnecessary_const: true
    unnecessary_new: true

    # ---- 代码质量 ----
    avoid_empty_else: true
    avoid_function_literals_in_foreach_calls: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_returning_null_for_future: true
    avoid_single_cascade_in_expression_statements: true
    avoid_unused_constructor_parameters: true
    cancel_subscriptions: true
    close_sinks: true
    empty_catches: false                    # 空 catch 块是否允许，可视团队习惯
    hash_and_equals: true
    no_duplicate_case_values: true
    prefer_is_not_empty: true
    unnecessary_getters_setters: true

    # ---- 命名规范 ----
    camel_case_extensions: true
    camel_case_types: true
    constant_identifier_names: false        # 是否允许常量大写命名（如 API_KEY）
    library_prefixes: true
    non_constant_identifier_names: false
    file_names: true                        # 文件名必须小写下划线

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
    - "build/**"

  errors:
    invalid_annotation_target: ignore
    unnecessary_import: warning
    deprecated_member_use_from_same_package: warning
