name: Flutter CI/CD with Pgyer

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 安装 Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.8"

      # 3. 获取依赖
      - name: Install dependencies
        run: flutter pub get

      # 4. 分析代码
      - name: Analyze
        run: flutter analyze

      # 5. 跑测试
      - name: Test
        run: flutter test

      # 6. 打包 APK
      - name: Build APK
        run: flutter build apk --release

      # 7. 上传到蒲公英
      - name: Upload to Pgyer
        run: |
          curl -F "file=@build/app/outputs/flutter-apk/app-release.apk" \
               -F "_api_key=${{ secrets.PGY_API_KEY }}" \
               -F "uKey=${{ secrets.PGY_USER_KEY }}" \
               https://www.pgyer.com/apiv2/app/upload
